### ISSUE TITLE
[Question] Standardization code

### ISSUE THREAD

**Issue by ikhsanalatsary** [Pamblam/jSQL#12]
Interesting idea & implementation. But not complete if there is no standardization of our code. It's for the quality of our code. Therefore we need to add Javascript Standard rules with eslint-config-standard or standard JS (https://standardjs.com/)

**Comment by Pamblam** [comment]
Great idea, thanks. I've added eslint to the [Code Climate config](https://github.com/Pamblam/jSQL/blob/master/.codeclimate.yml).
