### ISSUE TITLE
Readme graphics

### ISSUE THREAD

**Issue by Pamblam** [Pamblam/jSQL#8]
Anyone wanna make a graphic for the [jSQL readme](https://github.com/Pamblam/jSQL/blob/master/README.md) and get an easy PR for Hacktoberfest?

Specifically, a visual representation of the 3 layers described in the top of the readme:

> Under the hood, jSQL has 3 layers: 
> 
>  - **At the Lowest level**, jSQL automatically chooses the best method of storage to save state and interacts directly with it. This layer exposes a persistence method, [`jSQL.commit()`](https://github.com/Pamblam/jSQL/wiki/Persistence-Management#jsqlcommit), which is called to serialize and store all data currently in the jSQL database on the user's hard drive. While the app is open and loaded in the browser, this data is serialized and stored within reach in the [`jSQL.tables`](https://github.com/Pamblam/jSQL/wiki/Persistence-Management#jsqltables) object where the library is able to perform operations on it.
> 
>  - **In the middle**, a set of methods are used to build [`jSQLQuery` objects](https://github.com/Pamblam/jSQL/wiki/jSQLquery-interface) which execute CRUD commands on the jSQL database and it's tables. *(See: [`jSQL.createTable()`](https://github.com/Pamblam/jSQL/wiki/Querying-the-Database#jsqlcreatetableparams), [`jSQL.select()`](https://github.com/Pamblam/jSQL/wiki/Querying-the-Database#jsqlselectcolumns), [`jSQL.insertInto()`](https://github.com/Pamblam/jSQL/wiki/Querying-the-Database#jsqlinsertintotablename), [`jSQL.dropTable()`](https://github.com/Pamblam/jSQL/wiki/Querying-the-Database#jsqldroptabletablename), [`jSQL.update()`](https://github.com/Pamblam/jSQL/wiki/Querying-the-Database#jsqlupdatetablename), and [`jSQL.deleteFrom()`](https://github.com/Pamblam/jSQL/wiki/Querying-the-Database#jsqldeletefromtablename))*
> 
>  - **At the highest level**, jSQL is an SQL engine (hence the name: Javascript Query Language) which understands a subset of MySQL passed to the [`jSQL.query()`](https://github.com/Pamblam/jSQL/wiki/Querying-the-Database#jsqlquerysqlquery) method, which parses a [jSQL statement](https://github.com/Pamblam/jSQL/wiki/jSQL-Syntax) and uses the above methods to create [`jSQLQuery` objects](https://github.com/Pamblam/jSQL/wiki/jSQLquery-interface) to perform operations on the database.

You can upload it to imgur and put it in the readme, above the section quoted above.

**Comment by outofgamut** [comment]
I can help with this. Any specific visual? Feel free to scratch something out on paper and I can clean it up in a SVG.

**Comment by Pamblam** [comment]
Hi outofgamut, thank you!

I was thinking maybe some sort of flowchart, but honestly any way you can get the message across is fine. Mainly just looking to break up the text on the readme.

Here's the basic idea, sketched out on a tiny cell phone..

[![flowchart](https://i.imgur.com/S6Oa8ZS.png)](https://i.imgur.com/S6Oa8ZS.png)

Don't forget to wait til at least Saturday to submit a PR, if you do it before the 1st it won't count for Hacktoberfest :smiley:
